idle:
  color: [
    # white on the front, red on the back
    [1, 1, 1], # front left
    [1, 0, 0], # back right
    [1, 0, 0], # back left
    [1, 1, 1], # front right
    [1, 1, 1]  # front center
  ]
  intensity: [
    0.2,
    0.2,
    0.2,
    0.2,
    0.2
  ]
